version: '3'

services:
  equipment_db:
    image: postgres:14
    container_name: equipment_db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - equipment_net

  equipment_api:
    build: ./
    container_name: equipment_api
    restart: always
    command: bash -c "python main.py"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - equipment_db
    networks:
      - equipment_net


networks:
  equipment_net:
    external: true
